import { useState } from 'react'
import Chatbot from './components/Chatbot'
import Hyperspeed from './components/Hyperspeed'

const skillGroups = [
  { number: '01', title: 'PROGRAMMING', skills: ['Python', 'C / C++', 'JavaScript', 'TypeScript'] },
  { number: '02', title: 'AI / COMPUTER VISION', skills: ['YOLO', 'OpenCV', 'Machine Learning', 'Object Detection', 'Computer Vision'] },
  { number: '03', title: 'ROBOTICS', skills: ['ROS 2', 'SLAM', 'MAVLink', 'Pixhawk', 'Autonomous Navigation', 'Drone Systems'] },
  { number: '04', title: 'EMBEDDED & IOT', skills: ['ESP32', 'Arduino', 'Raspberry Pi', 'Sensors', 'Motor Controllers', 'IoT'] },
  { number: '05', title: 'WEB & BACKEND', skills: ['React', 'Vite', 'Next.js', 'FastAPI', 'Node.js', 'PostgreSQL', 'Supabase'] },
]
const projects = [
  { id: '01', name: 'AERIS', descriptor: 'AUTONOMOUS UAV', description: 'An autonomous UAV system focused on indoor navigation, mapping, computer vision, and survivor detection.', tags: ['ROS 2', 'PIXHAWK', 'MAVLINK', 'SLAM', 'YOLO', 'LIDAR'], features: ['Autonomous navigation & indoor mapping', 'RGB and thermal survivor detection', 'Ground control station integration'] },
  { id: '02', name: 'POTHOLE DETECTION', descriptor: 'AUTONOMOUS REPAIR ROBOT', description: 'A robotic system designed to detect potholes, estimate their depth and volume, and control a filling mechanism.', tags: ['YOLO', 'COMPUTER VISION', 'ARDUINO', 'ESP32', 'GPS'], features: ['Vision based pothole detection', 'Depth and volume estimation', 'Automated filling mechanism'] },
  { id: '03', name: 'FLOOD MONITOR', descriptor: 'SMART IOT SYSTEM', description: 'An IoT flood monitoring and prediction concept built around connected sensors and a live dashboard.', tags: ['ESP32', 'IOT', 'SENSORS', 'AI PREDICTION', 'FLUTTER'], features: ['Sensor based water level monitoring', 'Predictive alerts', 'Live dashboard concept'] },
  { id: '04', name: 'NEXSTEP', descriptor: 'AI CAREER GUIDANCE', description: 'An AI powered student career guidance platform to help students explore career paths, skills, and opportunities.', tags: ['AI', 'REACT', 'TYPESCRIPT', 'SUPABASE', 'POSTGRESQL'], features: ['Career path exploration', 'Skills and opportunity discovery', 'Student focused guidance'] },
  { id: '05', name: 'SOIL HEALTH ADVISOR', descriptor: 'AI FOR AGRICULTURE', description: 'An AI powered concept for analyzing soil information and suggesting ways to improve soil health and crop selection.', tags: ['AI', 'SOIL ANALYSIS', 'AGRICULTURE'], features: ['Soil information analysis', 'Soil improvement recommendations', 'Crop selection guidance'] },
  { id: '06', name: 'SMART CLASSROOM', descriptor: 'CONNECTED LEARNING', description: 'An intelligent classroom concept combining IoT, automation, and data driven monitoring.', tags: ['IOT', 'AUTOMATION', 'SENSORS'], features: ['Connected classroom monitoring', 'Automation concepts', 'Data driven insights'] },
]

export default function App() {
  const [isAIResponding, setIsAIResponding] = useState(false)
  const [chatOpenSignal, setChatOpenSignal] = useState(0)
  const askAmos = () => setChatOpenSignal(signal => signal + 1)
  return <>
    <Hyperspeed isAIResponding={isAIResponding} />
    <div className="site-shell">
      <header className="topbar"><a className="wordmark" href="#home" aria-label="Amos home">AMOS<span>.</span></a><nav aria-label="Main navigation"><a href="#about">ABOUT</a><a href="#skills">SKILLS</a><a href="#projects">PROJECTS</a><a href="#journey">JOURNEY</a><a href="#contact">CONTACT</a></nav><button className="nav-ai" onClick={askAmos}><span>✳</span> AI ASSISTANT <i /></button><a className="mobile-chat" href="#contact" onClick={event => { event.preventDefault(); askAmos() }}>AI <i /></a></header>
      <main>
        <section className="hero section-wrap" id="home"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> ECE · ROBOTICS · APPLIED AI <span className="eyebrow-index">PORTFOLIO / 2026</span></div><p className="hero-kicker">ENGINEERING THE PHYSICAL + DIGITAL</p><h1>AUGUSTINE<br/><span>AMOS A.</span></h1><div className="role-list"><span>ECE STUDENT</span><b>·</b><span>ROBOTICS BUILDER</span><b>·</b><span>AI / ML DEVELOPER</span></div><p className="hero-statement">Building intelligent machines that connect hardware, software and the real world.</p><div className="hero-actions"><a className="button button-primary" href="#projects">VIEW PROJECTS <span>↘</span></a><button className="button button-secondary" onClick={askAmos}>ASK MY AI <span>✳</span></button></div><div className="availability"><span className="live-dot" /> AVAILABLE FOR INTERNSHIPS / PROJECTS</div></div>
          <div className="hero-visual" aria-label="Abstract robotics engineering illustration"><div className="visual-top mono"><span>FIG 01 — FIELD SYSTEMS</span><span>12° 58′ N / 77° 35′ E</span></div><div className="radar"><div className="radar-ring ring-one"/><div className="radar-ring ring-two"/><div className="radar-ring ring-three"/><div className="radar-cross cross-x"/><div className="radar-cross cross-y"/><div className="radar-sweep"/><div className="radar-center"><span>AA</span></div><i className="radar-blip blip-one"/><i className="radar-blip blip-two"/><i className="radar-blip blip-three"/><span className="radar-caption mono">AUTONOMOUS SYSTEM / ACTIVE</span></div><div className="visual-bottom mono"><span>LATENCY <b>14 MS</b></span><span>SYS. READY <i /></span></div><span className="corner corner-tl"/><span className="corner corner-tr"/><span className="corner corner-bl"/><span className="corner corner-br"/></div></div><div className="hero-footer mono"><span>01 / INTRODUCTION</span><span>SCROLL TO EXPLORE <b>↓</b></span></div></section>

        <section className="section-wrap about-section" id="about"><div className="section-heading"><span className="section-index">01 — ABOUT</span><h2>Curious by nature.<br/><em>Engineer by practice.</em></h2></div><div className="about-layout"><div className="about-text"><p className="lead">I’m an Electronics and Communication Engineering student exploring the point where intelligent software meets the physical world.</p><p>My work and interests span robotics, computer vision, embedded systems, autonomous UAVs, IoT, and software development. I enjoy bringing complex systems together — from sensors and flight controllers to the code that helps machines perceive and act.</p><p>There’s always another prototype to build, system to understand, or problem worth solving.</p><a className="text-link" href="#contact">LET’S CONNECT <span>↗</span></a></div><div className="info-panel">{[['DISCIPLINE','Electronics & Communication Engineering'],['FOCUS','Robotics / AI / Embedded Systems'],['CURRENTLY BUILDING','Autonomous UAV Systems'],['INTERESTS','Computer Vision / ROS 2 / Autonomous Navigation']].map(([label,value],index)=><div className="info-row" key={label}><span className="mono">0{index+1} / {label}</span><strong>{value}</strong><span className="row-plus">↗</span></div>)}</div></div></section>

        <section className="section-wrap skills-section" id="skills"><div className="section-heading compact"><span className="section-index">02 — CAPABILITIES</span><h2>Tools for making<br/><em>ideas tangible.</em></h2><p>A growing toolkit across software, intelligent systems, and hardware.</p></div><div className="skills-grid">{skillGroups.map(group=><article className="skill-card" key={group.number}><div className="skill-card-top"><span className="mono">{group.number} / CAPABILITY</span><span>↗</span></div><h3>{group.title}</h3><div className="tag-list">{group.skills.map(skill=><span className="skill-tag" key={skill}>{skill}</span>)}</div></article>)}</div></section>

        <section className="section-wrap projects-section" id="projects"><div className="projects-title"><div className="section-heading compact"><span className="section-index">03 — SELECTED WORK</span><h2>Built to meet<br/><em>the real world.</em></h2></div><p>Systems, prototypes, and ideas exploring how engineering can solve practical problems.</p></div><div className="project-grid">{projects.map(project=><article className="project-card" key={project.id}><div className="project-card-head"><span className="mono">PROJECT / {project.id}</span><span className="project-mark">↗</span></div><div className={`project-art art-${project.id}`} aria-hidden="true"><div className="art-grid"/><div className="art-orbit orbit-a"/><div className="art-orbit orbit-b"/><div className="art-core">{project.id === '01' ? 'A' : project.id === '02' ? 'R' : project.id === '03' ? '◉' : project.id === '04' ? 'N' : '⌁'}</div><span className="art-label mono">{project.descriptor}</span><span className="art-coordinate mono">SYS / {project.id}</span></div><div className="project-name"><h3>{project.name}</h3><span>{project.descriptor}</span></div><p className="project-description">{project.description}</p><div className="tag-list project-tags">{project.tags.map(tag=><span className="skill-tag" key={tag}>{tag}</span>)}</div><ul className="feature-list">{project.features.map(feature=><li key={feature}>{feature}</li>)}</ul><div className="project-links"><a href="#contact" onClick={event=>{event.preventDefault();askAmos()}}>GITHUB <span>↗</span></a><a href="#contact" onClick={event=>{event.preventDefault();askAmos()}}>DEMO <span>↗</span></a></div></article>)}</div><p className="project-note mono">PROJECT LINKS WILL BE ADDED AS REPOSITORIES AND DEMOS BECOME AVAILABLE.</p></section>

        <section className="section-wrap journey-section" id="journey"><div className="section-heading compact"><span className="section-index">04 — JOURNEY</span><h2>Learning through<br/><em>building.</em></h2></div><div className="journey-card"><div className="journey-symbol">✳</div><span className="mono">A CONTINUOUS PRACTICE</span><p>Exploring electronics and communication engineering through hands-on work in robotics, autonomous systems, AI, and embedded development.</p><span className="journey-foot mono">EDUCATION · PROJECTS · EXPERIMENTS</span></div></section>

        <section className="section-wrap contact-section" id="contact"><div className="contact-inner"><span className="section-index">05 — CONTACT</span><p className="contact-overline">HAVE A CHALLENGE IN MIND?</p><h2>LET’S BUILD<br/><em>SOMETHING.</em></h2><p className="contact-copy">Have an idea, project, internship opportunity,<br/>or engineering challenge?<br/><strong>Let’s connect.</strong></p><div className="contact-links"><a href="mailto:" aria-label="Email Augustine (address not provided)">EMAIL <span>↗</span></a><a href="#contact" onClick={event=>{event.preventDefault();askAmos()}}>GITHUB <span>↗</span></a><a href="#contact" onClick={event=>{event.preventDefault();askAmos()}}>LINKEDIN <span>↗</span></a></div><span className="contact-watermark">AA</span></div></section>
      </main>
      <footer className="footer mono"><a className="wordmark" href="#home">AMOS<span>.</span></a><span>© 2026 AUGUSTINE AMOS A.</span><span className="footer-status"><i/> SYSTEM STATUS: ONLINE</span><a href="#home">BACK TO TOP ↑</a></footer>
    </div>
    <Chatbot isAIResponding={isAIResponding} setIsAIResponding={setIsAIResponding} openSignal={chatOpenSignal} />
  </>
}
